name: MC Update File Generation

on:
  repository_dispatch:
    types: [minecraft-update]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm install @types/node
      - run: node scripts/generateLists.mjs
      - run: git config --global user.name "MC Update"
      - run: git add --all
      - run: git commit "Updated generated files for new mc release"
      - run: git push
