name: Node.js Publish Pre-Release

on:
  release:
    types: [prereleased]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -f --production
      - run: npm install @types/node
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./dist/.npmrc
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
      - run: cd dist && npm publish dist --tag next
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
